// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksApi.Models;

namespace ParksApi.Migrations
{
    [DbContext(typeof(ParksApiContext))]
    [Migration("20210208041528_ManyParks")]
    partial class ManyParks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired();

                    b.Property<string>("StateOrNational")
                        .IsRequired();

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Name = "Rickwood Caverns",
                            State = "Alabama",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 2,
                            Name = "Cathedral Caverns",
                            State = "Alabama",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 3,
                            Name = "Gulf",
                            State = "Alabama",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 4,
                            Name = "Denali",
                            State = "Alaska",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 5,
                            Name = "Kachemak",
                            State = "Alaska",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 6,
                            Name = "Wood-Tikchik",
                            State = "Alaska",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 7,
                            Name = "Denali",
                            State = "Alaska",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 8,
                            Name = "Gates of the Arctic",
                            State = "Alaska",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 9,
                            Name = "Glacier Bay",
                            State = "Alaska",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 10,
                            Name = "Katmai",
                            State = "Alaska",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 11,
                            Name = "Kenai Fjords",
                            State = "Alaska",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 12,
                            Name = "Kobuk Valley",
                            State = "Alaska",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 13,
                            Name = "Lake Clark",
                            State = "Alaska",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 14,
                            Name = "Wrangell–St. Elias",
                            State = "Alaska",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 15,
                            Name = "American Samoa",
                            State = "American Samoa",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 16,
                            Name = "Kartchner Caverns",
                            State = "Arizona",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 17,
                            Name = "Slide Rock",
                            State = "Arizona",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 18,
                            Name = "Red Rock",
                            State = "Arizona",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 19,
                            Name = "Grand Canyon",
                            State = "Arizona",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 20,
                            Name = "Petrified Forest",
                            State = "Arizona",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 21,
                            Name = "Saguaro",
                            State = "Arizona",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 22,
                            Name = "Devil’s Den",
                            State = "Arkansas",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 23,
                            Name = "Bull Shoals-White River",
                            State = "Arkansas",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 24,
                            Name = "Cane Creek",
                            State = "Arkansas",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 25,
                            Name = "Hot Springs",
                            State = "Arkansas",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 26,
                            Name = "Crystal Cove",
                            State = "California",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 27,
                            Name = "Jedediah Smith Redwoods",
                            State = "California",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 28,
                            Name = "Julia Pfeiffer Burns",
                            State = "California",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 29,
                            Name = "Yosemite",
                            State = "California",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 30,
                            Name = "Channel Islands",
                            State = "California",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 31,
                            Name = "Joshua Tree",
                            State = "California",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 32,
                            Name = "Kings Canyon",
                            State = "California",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 33,
                            Name = "Lassen Volcanic",
                            State = "California",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 34,
                            Name = "Pinnacles",
                            State = "California",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 35,
                            Name = "Redwood",
                            State = "California",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 36,
                            Name = "Sequoia",
                            State = "California",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 37,
                            Name = "Death Valley",
                            State = "California, Nevada",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 38,
                            Name = "Mueller",
                            State = "Colorado",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 39,
                            Name = "State Forest",
                            State = "Colorado",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 40,
                            Name = "Fishers Peak",
                            State = "Colorado",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 41,
                            Name = "Black Canyon of the Gunnison",
                            State = "Colorado",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 42,
                            Name = "Great Sand Dunes",
                            State = "Colorado",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 43,
                            Name = "Mesa Verde",
                            State = "Colorado",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 44,
                            Name = "Rocky Mountain",
                            State = "Colorado",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 45,
                            Name = "Dinosaur",
                            State = "Connecticut",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 46,
                            Name = "Kent Falls",
                            State = "Connecticut",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 47,
                            Name = "Rocky Neck",
                            State = "Connecticut",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 48,
                            Name = "Cape Henlopen",
                            State = "Delaware",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 49,
                            Name = "Trap Pond",
                            State = "Delaware",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 50,
                            Name = "Fort Delaware",
                            State = "Delaware",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 51,
                            Name = "Blue Spring",
                            State = "Florida",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 52,
                            Name = "Florida Caverns",
                            State = "Florida",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 53,
                            Name = "Fort De Soto",
                            State = "Florida",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 54,
                            Name = "Biscayne",
                            State = "Florida",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 55,
                            Name = "Dry Tortugas",
                            State = "Florida",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 56,
                            Name = "Everglades",
                            State = "Florida",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 57,
                            Name = "Cloudland Canyon",
                            State = "Georgia",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 58,
                            Name = "Fort Yargo",
                            State = "Georgia",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 59,
                            Name = "Tallulah Gorge",
                            State = "Georgia",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 60,
                            Name = "Akaka Falls",
                            State = "Hawaii",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 61,
                            Name = "Waiʻānapanapa",
                            State = "Hawaii",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 62,
                            Name = "Waimea Canyon",
                            State = "Hawaii",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 63,
                            Name = "Haleakalā",
                            State = "Hawaii",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 64,
                            Name = "Hawaiʻi Volcanoes",
                            State = "Hawaii",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 65,
                            Name = "Bruneau Dunes",
                            State = "Idaho",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 66,
                            Name = "Harriman",
                            State = "Idaho",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 67,
                            Name = "Priest Lake",
                            State = "Idaho",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 68,
                            Name = "Hennepin Canal Parkway",
                            State = "Illinois",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 69,
                            Name = "South Shore",
                            State = "Illinois",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 70,
                            Name = "Starved Rock",
                            State = "Illinois",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 71,
                            Name = "Brown County",
                            State = "Indiana",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 72,
                            Name = "Chain O’ Lakes",
                            State = "Indiana",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 73,
                            Name = "Turkey Run",
                            State = "Indiana",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 74,
                            Name = "Indiana Dunes",
                            State = "Indiana",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 75,
                            Name = "Backbone",
                            State = "Iowa",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 76,
                            Name = "Beed's Lake",
                            State = "Iowa",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 77,
                            Name = "Pikes Peak",
                            State = "Iowa",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 78,
                            Name = "Kanopolis",
                            State = "Kansas",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 79,
                            Name = "Scott",
                            State = "Kansas",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 80,
                            Name = "Wilson",
                            State = "Kansas",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 81,
                            Name = "Cumberland Falls",
                            State = "Kentucky",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 82,
                            Name = "Daniel Boone",
                            State = "Kentucky",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 83,
                            Name = "Natural Bridge",
                            State = "Kentucky",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 84,
                            Name = "Mammoth Cave",
                            State = "Kentucky",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 85,
                            Name = "Chicot",
                            State = "Louisiana",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 86,
                            Name = "Lake Fausse Pointe",
                            State = "Louisiana",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 87,
                            Name = "Fontainebleau",
                            State = "Louisiana",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 88,
                            Name = "Mt. Blue",
                            State = "Maine",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 89,
                            Name = "Quoddy Head",
                            State = "Maine",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 90,
                            Name = "Reid",
                            State = "Maine",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 91,
                            Name = "Acadia",
                            State = "Maine",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 92,
                            Name = "Assateague",
                            State = "Maryland",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 93,
                            Name = "Elk Neck",
                            State = "Maryland",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 94,
                            Name = "Point Lookout",
                            State = "Maryland",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 95,
                            Name = "Bash Bish Falls",
                            State = "Massachusetts",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 96,
                            Name = "Boston Harbor Islands",
                            State = "Massachusetts",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 97,
                            Name = "Mount Greylock",
                            State = "Massachusetts",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 98,
                            Name = "Belle Isle",
                            State = "Michigan",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 99,
                            Name = "Laughing Whitefish Falls",
                            State = "Michigan",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 100,
                            Name = "Porcupine Mountains Wilderness",
                            State = "Michigan",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 101,
                            Name = "Isle Royale",
                            State = "Michigan",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 102,
                            Name = "George H. Crosby Manitou",
                            State = "Minnesota",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 103,
                            Name = "Itasca",
                            State = "Minnesota",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 104,
                            Name = "Minneopa",
                            State = "Minnesota",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 105,
                            Name = "Voyageurs",
                            State = "Minnesota",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 106,
                            Name = "LeFleur's Bluff",
                            State = "Mississippi",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 107,
                            Name = "Tishomingo",
                            State = "Mississippi",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 108,
                            Name = "Shepard State",
                            State = "Mississippi",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 109,
                            Name = "Johnson’s Shut-Ins",
                            State = "Missouri",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 110,
                            Name = "Knob Knoster",
                            State = "Missouri",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 111,
                            Name = "Prairie",
                            State = "Missouri",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 112,
                            Name = "Gateway Arch",
                            State = "Missouri",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 113,
                            Name = "Makoshika",
                            State = "Montana",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 114,
                            Name = "Rosebud Battlefield",
                            State = "Montana",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 115,
                            Name = "Pictograph Cave",
                            State = "Montana",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 116,
                            Name = "Glacier",
                            State = "Montana",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 117,
                            Name = "Eugene T. Mahoney",
                            State = "Nebraska",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 118,
                            Name = "Fort Robinson",
                            State = "Nebraska",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 119,
                            Name = "Wildcat Hills",
                            State = "Nebraska",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 120,
                            Name = "Lake Tahoe",
                            State = "Nevada",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 121,
                            Name = "Valley of Fire",
                            State = "Nevada",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 122,
                            Name = "Cave Lake Slate",
                            State = "Nevada",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 123,
                            Name = "Great Basin",
                            State = "Nevada",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 124,
                            Name = "Crawford Notch",
                            State = "New Hampshire",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 125,
                            Name = "Franconia Notch",
                            State = "New Hampshire",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 126,
                            Name = "Bear Brook",
                            State = "New Hampshire",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 127,
                            Name = "Island Beach",
                            State = "New Jersey",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 128,
                            Name = "Liberty State Park",
                            State = "New Jersey",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 129,
                            Name = "Pigeon Swamp",
                            State = "New Jersey",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 130,
                            Name = "Bottomless Lakes",
                            State = "New Mexico",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 131,
                            Name = "City of Rocks",
                            State = "New Mexico",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 132,
                            Name = "Elephant Butte",
                            State = "New Mexico",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 133,
                            Name = "Carlsbad Caverns",
                            State = "New Mexico",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 134,
                            Name = "White Sands",
                            State = "New Mexico",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 135,
                            Name = "Adirondack",
                            State = "New York",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 136,
                            Name = "Niagara Falls",
                            State = "New York",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 137,
                            Name = "Sterling Forest",
                            State = "New York",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 138,
                            Name = "Chimney Rock",
                            State = "North Carolina",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 139,
                            Name = "Fort Macon",
                            State = "North Carolina",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 140,
                            Name = "Hanging Rock",
                            State = "North Carolina",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 141,
                            Name = "Great Smoky Mountains",
                            State = "North Carolina, Tennessee",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 142,
                            Name = "Fort Abraham Lincoln",
                            State = "North Dakota",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 143,
                            Name = "Little Missouri",
                            State = "North Dakota",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 144,
                            Name = "Lake Metigoshe",
                            State = "North Dakota",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 145,
                            Name = "Theodore Roosevelt",
                            State = "North Dakota",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 146,
                            Name = "Hocking Hills",
                            State = "Ohio",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 147,
                            Name = "Salt Fork",
                            State = "Ohio",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 148,
                            Name = "Punderson",
                            State = "Ohio",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 149,
                            Name = "Cuyahoga Valley",
                            State = "Ohio",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 150,
                            Name = "Beavers Bend",
                            State = "Oklahoma",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 151,
                            Name = "Lake Thunderbird",
                            State = "Oklahoma",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 152,
                            Name = "Robbers Cave",
                            State = "Oklahoma",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 153,
                            Name = "Ecola",
                            State = "Oregon",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 154,
                            Name = "Milo McIver",
                            State = "Oregon",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 155,
                            Name = "Smith Rock",
                            State = "Oregon",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 156,
                            Name = "Crater Lake",
                            State = "Oregon",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 157,
                            Name = "Cherry Springs",
                            State = "Pennsylvania",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 158,
                            Name = "Cook Forest",
                            State = "Pennsylvania",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 159,
                            Name = "Presque Isle",
                            State = "Pennsylvania",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 160,
                            Name = "Beavertail",
                            State = "Rhode Island",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 161,
                            Name = "Snake Den",
                            State = "Rhode Island",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 162,
                            Name = "Colt",
                            State = "Rhode Island",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 163,
                            Name = "Hunting Island",
                            State = "South Carolina",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 164,
                            Name = "Mountain Bridge Wilderness Area",
                            State = "South Carolina",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 165,
                            Name = "Table Rock",
                            State = "South Carolina",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 166,
                            Name = "Congaree",
                            State = "South Carolina",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 167,
                            Name = "Custer",
                            State = "South Dakota",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 168,
                            Name = "Bear Butte",
                            State = "South Dakota",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 169,
                            Name = "Sica Hollow",
                            State = "South Dakota",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 170,
                            Name = "Badlands",
                            State = "South Dakota",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 171,
                            Name = "Wind Cave",
                            State = "South Dakota",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 172,
                            Name = "Fall Creek Falls",
                            State = "Tennessee",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 173,
                            Name = "South Cumberland",
                            State = "Tennessee",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 174,
                            Name = "Roan Mountain",
                            State = "Tennessee",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 175,
                            Name = "Big Bend Ranch",
                            State = "Texas",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 176,
                            Name = "Palo Duro Canyon",
                            State = "Texas",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 177,
                            Name = "Falcon",
                            State = "Texas",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 178,
                            Name = "Big Bend",
                            State = "Texas",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 179,
                            Name = "Guadalupe Mountains",
                            State = "Texas",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 180,
                            Name = "Virgin Islands",
                            State = "U.S. Virgin Islands",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 181,
                            Name = "Dead Horse Point",
                            State = "Utah",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 182,
                            Name = "Goblin Valley",
                            State = "Utah",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 183,
                            Name = "Jordanelle Reservoir",
                            State = "Utah",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 184,
                            Name = "Zion",
                            State = "Utah",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 185,
                            Name = "Arches",
                            State = "Utah",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 186,
                            Name = "Bryce Canyon",
                            State = "Utah",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 187,
                            Name = "Canyonlands",
                            State = "Utah",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 188,
                            Name = "Capitol Reef",
                            State = "Utah",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 189,
                            Name = "Ricker Pond",
                            State = "Vermont",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 190,
                            Name = "Smugglers’ Notch",
                            State = "Vermont",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 191,
                            Name = "Camel’s Hump",
                            State = "Vermont",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 192,
                            Name = "First Landing",
                            State = "Virginia",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 193,
                            Name = "Grayson Highlands",
                            State = "Virginia",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 194,
                            Name = "Shenandoah River",
                            State = "Virginia",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 195,
                            Name = "Shenandoah",
                            State = "Virginia",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 196,
                            Name = "Cape Disappointment",
                            State = "Washington",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 197,
                            Name = "Deception Pass",
                            State = "Washington",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 198,
                            Name = "Wallas Falls",
                            State = "Washington",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 199,
                            Name = "Mount Rainier",
                            State = "Washington",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 200,
                            Name = "North Cascades",
                            State = "Washington",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 201,
                            Name = "Olympic",
                            State = "Washington",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 202,
                            Name = "Blackwater Falls",
                            State = "West Virginia",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 203,
                            Name = "Watoga",
                            State = "West Virginia",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 204,
                            Name = "Babcock",
                            State = "West Virginia",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 205,
                            Name = "New River Gorge",
                            State = "West Virginia",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 206,
                            Name = "Devil’s Lake",
                            State = "Wisconsin",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 207,
                            Name = "Lakeshore",
                            State = "Wisconsin",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 208,
                            Name = "Peninsula",
                            State = "Wisconsin",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 209,
                            Name = "Glendo",
                            State = "Wyoming",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 210,
                            Name = "Seminoe",
                            State = "Wyoming",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 211,
                            Name = "Hot Springs",
                            State = "Wyoming",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 212,
                            Name = "Grand Teton",
                            State = "Wyoming",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 213,
                            Name = "Yellowstone",
                            State = "Wyoming, Montana, Idaho",
                            StateOrNational = "National"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
