using Microsoft.EntityFrameworkCore;

namespace ParksApi.Models
{
  public class ParksApiContext : DbContext
  {
    public ParksApiContext(DbContextOptions<ParksApiContext> options)
    : base(options)
    {}

    public DbSet<Park> Parks {get;set;}

    protected override void OnModelCreating(ModelBuilder builder)
    {
      builder.Entity<Park>()
      .HasData(
        new Park { ParkId =001, 	Name = "Rickwood Caverns", 	                  State = "Alabama", 	                    StateOrNational = "State" },
        new Park { ParkId =002, 	Name = "Cathedral Caverns", 	                State = "Alabama", 	                    StateOrNational = "State" },
        new Park { ParkId =003, 	Name = "Gulf", 	                              State = "Alabama", 	                    StateOrNational = "State" },
        new Park { ParkId =004, 	Name = "Denali", 	                            State = "Alaska", 	                    StateOrNational = "State" },
        new Park { ParkId =005, 	Name = "Kachemak", 	                          State = "Alaska", 	                    StateOrNational = "State" },
        new Park { ParkId =006, 	Name = "Wood-Tikchik", 	                      State = "Alaska", 	                    StateOrNational = "State" },
        new Park { ParkId =007, 	Name = "Denali", 	                            State = "Alaska", 	                    StateOrNational = "National" },
        new Park { ParkId =008, 	Name = "Gates of the Arctic", 	              State = "Alaska", 	                    StateOrNational = "National" },
        new Park { ParkId =009, 	Name = "Glacier Bay", 	                      State = "Alaska", 	                    StateOrNational = "National" },
        new Park { ParkId =010, 	Name = "Katmai", 	                            State = "Alaska", 	                    StateOrNational = "National" },
        new Park { ParkId =011, 	Name = "Kenai Fjords", 	                      State = "Alaska", 	                    StateOrNational = "National" },
        new Park { ParkId =012, 	Name = "Kobuk Valley", 	                      State = "Alaska", 	                    StateOrNational = "National" },
        new Park { ParkId =013, 	Name = "Lake Clark", 	                        State = "Alaska", 	                    StateOrNational = "National" },
        new Park { ParkId =014, 	Name = "Wrangell–St. Elias", 	                State = "Alaska", 	                    StateOrNational = "National" },
        new Park { ParkId =015, 	Name = "American Samoa", 	                    State = "American Samoa", 	            StateOrNational = "National" },
        new Park { ParkId =016, 	Name = "Kartchner Caverns", 	                State = "Arizona", 	                    StateOrNational = "State" },
        new Park { ParkId =017, 	Name = "Slide Rock", 	                        State = "Arizona", 	                    StateOrNational = "State" },
        new Park { ParkId =018, 	Name = "Red Rock", 	                          State = "Arizona", 	                    StateOrNational = "State" },
        new Park { ParkId =019, 	Name = "Grand Canyon", 	                      State = "Arizona", 	                    StateOrNational = "National" },
        new Park { ParkId =020, 	Name = "Petrified Forest", 	                  State = "Arizona", 	                    StateOrNational = "National" },
        new Park { ParkId =021, 	Name = "Saguaro", 	                          State = "Arizona", 	                    StateOrNational = "National" },
        new Park { ParkId =022, 	Name = "Devil’s Den", 	                      State = "Arkansas", 	                  StateOrNational = "State" },
        new Park { ParkId =023, 	Name = "Bull Shoals-White River", 	          State = "Arkansas", 	                  StateOrNational = "State" },
        new Park { ParkId =024, 	Name = "Cane Creek", 	                        State = "Arkansas", 	                  StateOrNational = "State" },
        new Park { ParkId =025, 	Name = "Hot Springs", 	                      State = "Arkansas", 	                  StateOrNational = "National" },
        new Park { ParkId =026, 	Name = "Crystal Cove", 	                      State = "California", 	                StateOrNational = "State" },
        new Park { ParkId =027, 	Name = "Jedediah Smith Redwoods", 	          State = "California", 	                StateOrNational = "State" },
        new Park { ParkId =028, 	Name = "Julia Pfeiffer Burns", 	              State = "California", 	                StateOrNational = "State" },
        new Park { ParkId =029, 	Name = "Yosemite", 	                          State = "California", 	                StateOrNational = "National" },
        new Park { ParkId =030, 	Name = "Channel Islands", 	                  State = "California", 	                StateOrNational = "National" },
        new Park { ParkId =031, 	Name = "Joshua Tree", 	                      State = "California", 	                StateOrNational = "National" },
        new Park { ParkId =032, 	Name = "Kings Canyon", 	                      State = "California", 	                StateOrNational = "National" },
        new Park { ParkId =033, 	Name = "Lassen Volcanic", 	                  State = "California", 	                StateOrNational = "National" },
        new Park { ParkId =034, 	Name = "Pinnacles", 	                        State = "California", 	                StateOrNational = "National" },
        new Park { ParkId =035, 	Name = "Redwood", 	                          State = "California", 	                StateOrNational = "National" },
        new Park { ParkId =036, 	Name = "Sequoia", 	                          State = "California", 	                StateOrNational = "National" },
        new Park { ParkId =037, 	Name = "Death Valley", 	                      State = "California, Nevada", 	        StateOrNational = "National" },
        new Park { ParkId =038, 	Name = "Mueller", 	                          State = "Colorado", 	                  StateOrNational = "State" },
        new Park { ParkId =039, 	Name = "State Forest", 	                      State = "Colorado", 	                  StateOrNational = "State" },
        new Park { ParkId =040, 	Name = "Fishers Peak", 	                      State = "Colorado", 	                  StateOrNational = "State" },
        new Park { ParkId =041, 	Name = "Black Canyon of the Gunnison",        State = "Colorado", 	                  StateOrNational = "National" },
        new Park { ParkId =042, 	Name = "Great Sand Dunes", 	                  State = "Colorado", 	                  StateOrNational = "National" },
        new Park { ParkId =043, 	Name = "Mesa Verde", 	                        State = "Colorado", 	                  StateOrNational = "National" },
        new Park { ParkId =044, 	Name = "Rocky Mountain", 	                    State = "Colorado", 	                  StateOrNational = "National" },
        new Park { ParkId =045, 	Name = "Dinosaur", 	                          State = "Connecticut", 	                StateOrNational = "State" },
        new Park { ParkId =046, 	Name = "Kent Falls", 	                        State = "Connecticut", 	                StateOrNational = "State" },
        new Park { ParkId =047, 	Name = "Rocky Neck", 	                        State = "Connecticut", 	                StateOrNational = "State" },
        new Park { ParkId =048, 	Name = "Cape Henlopen", 	                    State = "Delaware", 	                  StateOrNational = "State" },
        new Park { ParkId =049, 	Name = "Trap Pond", 	                        State = "Delaware", 	                  StateOrNational = "State" },
        new Park { ParkId =050, 	Name = "Fort Delaware", 	                    State = "Delaware", 	                  StateOrNational = "State" },
        new Park { ParkId =051, 	Name = "Blue Spring", 	                      State = "Florida", 	                    StateOrNational = "State" },
        new Park { ParkId =052, 	Name = "Florida Caverns", 	                  State = "Florida", 	                    StateOrNational = "State" },
        new Park { ParkId =053, 	Name = "Fort De Soto", 	                      State = "Florida", 	                    StateOrNational = "State" },
        new Park { ParkId =054, 	Name = "Biscayne", 	                          State = "Florida", 	                    StateOrNational = "National" },
        new Park { ParkId =055, 	Name = "Dry Tortugas", 	                      State = "Florida", 	                    StateOrNational = "National" },
        new Park { ParkId =056, 	Name = "Everglades", 	                        State = "Florida", 	                    StateOrNational = "National" },
        new Park { ParkId =057, 	Name = "Cloudland Canyon", 	                  State = "Georgia", 	                    StateOrNational = "State" },
        new Park { ParkId =058, 	Name = "Fort Yargo", 	                        State = "Georgia", 	                    StateOrNational = "State" },
        new Park { ParkId =059, 	Name = "Tallulah Gorge", 	                    State = "Georgia", 	                    StateOrNational = "State" },
        new Park { ParkId =060, 	Name = "Akaka Falls", 	                      State = "Hawaii", 	                    StateOrNational = "State" },
        new Park { ParkId =061, 	Name = "Waiʻānapanapa", 	                    State = "Hawaii", 	                    StateOrNational = "State" },
        new Park { ParkId =062, 	Name = "Waimea Canyon", 	                    State = "Hawaii", 	                    StateOrNational = "State" },
        new Park { ParkId =063, 	Name = "Haleakalā", 	                        State = "Hawaii", 	                    StateOrNational = "National" },
        new Park { ParkId =064, 	Name = "Hawaiʻi Volcanoes", 	                State = "Hawaii", 	                    StateOrNational = "National" },
        new Park { ParkId =065, 	Name = "Bruneau Dunes", 	                    State = "Idaho", 	                      StateOrNational = "State" },
        new Park { ParkId =066, 	Name = "Harriman", 	                          State = "Idaho", 	                      StateOrNational = "State" },
        new Park { ParkId =067, 	Name = "Priest Lake", 	                      State = "Idaho", 	                      StateOrNational = "State" },
        new Park { ParkId =068, 	Name = "Hennepin Canal Parkway", 	            State = "Illinois", 	                  StateOrNational = "State" },
        new Park { ParkId =069, 	Name = "South Shore", 	                      State = "Illinois", 	                  StateOrNational = "State" },
        new Park { ParkId =070, 	Name = "Starved Rock", 	                      State = "Illinois", 	                  StateOrNational = "State" },
        new Park { ParkId =071, 	Name = "Brown County", 	                      State = "Indiana", 	                    StateOrNational = "State" },
        new Park { ParkId =072, 	Name = "Chain O’ Lakes", 	                    State = "Indiana", 	                    StateOrNational = "State" },
        new Park { ParkId =073, 	Name = "Turkey Run", 	                        State = "Indiana", 	                    StateOrNational = "State" },
        new Park { ParkId =074, 	Name = "Indiana Dunes", 	                    State = "Indiana", 	                    StateOrNational = "National" },
        new Park { ParkId =075, 	Name = "Backbone", 	                          State = "Iowa", 	                      StateOrNational = "State" },
        new Park { ParkId =076, 	Name = "Beed's Lake", 	                      State = "Iowa", 	                      StateOrNational = "State" },
        new Park { ParkId =077, 	Name = "Pikes Peak", 	                        State = "Iowa", 	                      StateOrNational = "State" },
        new Park { ParkId =078, 	Name = "Kanopolis", 	                        State = "Kansas", 	                    StateOrNational = "State" },
        new Park { ParkId =079, 	Name = "Scott", 	                            State = "Kansas", 	                    StateOrNational = "State" },
        new Park { ParkId =080, 	Name = "Wilson", 	                            State = "Kansas", 	                    StateOrNational = "State" },
        new Park { ParkId =081, 	Name = "Cumberland Falls", 	                  State = "Kentucky", 	                  StateOrNational = "State" },
        new Park { ParkId =082, 	Name = "Daniel Boone", 	                      State = "Kentucky", 	                  StateOrNational = "State" },
        new Park { ParkId =083, 	Name = "Natural Bridge", 	                    State = "Kentucky", 	                  StateOrNational = "State" },
        new Park { ParkId =084, 	Name = "Mammoth Cave", 	                      State = "Kentucky", 	                  StateOrNational = "National" },
        new Park { ParkId =085, 	Name = "Chicot", 	                            State = "Louisiana", 	                  StateOrNational = "State" },
        new Park { ParkId =086, 	Name = "Lake Fausse Pointe", 	                State = "Louisiana", 	                  StateOrNational = "State" },
        new Park { ParkId =087, 	Name = "Fontainebleau", 	                    State = "Louisiana", 	                  StateOrNational = "State" },
        new Park { ParkId =088, 	Name = "Mt. Blue", 	                          State = "Maine", 	                      StateOrNational = "State" },
        new Park { ParkId =089, 	Name = "Quoddy Head", 	                      State = "Maine", 	                      StateOrNational = "State" },
        new Park { ParkId =090, 	Name = "Reid", 	                              State = "Maine", 	                      StateOrNational = "State" },
        new Park { ParkId =091, 	Name = "Acadia", 	                            State = "Maine", 	                      StateOrNational = "National" },
        new Park { ParkId =092, 	Name = "Assateague", 	                        State = "Maryland", 	                  StateOrNational = "State" },
        new Park { ParkId =093, 	Name = "Elk Neck", 	                          State = "Maryland", 	                  StateOrNational = "State" },
        new Park { ParkId =094, 	Name = "Point Lookout", 	                    State = "Maryland", 	                  StateOrNational = "State" },
        new Park { ParkId =095, 	Name = "Bash Bish Falls", 	                  State = "Massachusetts", 	              StateOrNational = "State" },
        new Park { ParkId =096, 	Name = "Boston Harbor Islands", 	            State = "Massachusetts", 	              StateOrNational = "State" },
        new Park { ParkId =097, 	Name = "Mount Greylock", 	                    State = "Massachusetts", 	              StateOrNational = "State" },
        new Park { ParkId =098, 	Name = "Belle Isle", 	                        State = "Michigan", 	                  StateOrNational = "State" },
        new Park { ParkId =099, 	Name = "Laughing Whitefish Falls", 	          State = "Michigan", 	                  StateOrNational = "State" },
        new Park { ParkId =100, 	Name = "Porcupine Mountains Wilderness",      State = "Michigan", 	                  StateOrNational = "State" },
        new Park { ParkId =101, 	Name = "Isle Royale", 	                      State = "Michigan", 	                  StateOrNational = "National" },
        new Park { ParkId =102, 	Name = "George H. Crosby Manitou", 	          State = "Minnesota", 	                  StateOrNational = "State" },
        new Park { ParkId =103, 	Name = "Itasca", 	                            State = "Minnesota", 	                  StateOrNational = "State" },
        new Park { ParkId =104, 	Name = "Minneopa", 	                          State = "Minnesota", 	                  StateOrNational = "State" },
        new Park { ParkId =105, 	Name = "Voyageurs", 	                        State = "Minnesota", 	                  StateOrNational = "National" },
        new Park { ParkId =106, 	Name = "LeFleur's Bluff", 	                  State = "Mississippi", 	                StateOrNational = "State" },
        new Park { ParkId =107, 	Name = "Tishomingo", 	                        State = "Mississippi", 	                StateOrNational = "State" },
        new Park { ParkId =108, 	Name = "Shepard State", 	                    State = "Mississippi", 	                StateOrNational = "State" },
        new Park { ParkId =109, 	Name = "Johnson’s Shut-Ins", 	                State = "Missouri", 	                  StateOrNational = "State" },
        new Park { ParkId =110, 	Name = "Knob Knoster", 	                      State = "Missouri", 	                  StateOrNational = "State" },
        new Park { ParkId =111, 	Name = "Prairie", 	                          State = "Missouri", 	                  StateOrNational = "State" },
        new Park { ParkId =112, 	Name = "Gateway Arch", 	                      State = "Missouri", 	                  StateOrNational = "National" },
        new Park { ParkId =113, 	Name = "Makoshika", 	                        State = "Montana", 	                    StateOrNational = "State" },
        new Park { ParkId =114, 	Name = "Rosebud Battlefield", 	              State = "Montana", 	                    StateOrNational = "State" },
        new Park { ParkId =115, 	Name = "Pictograph Cave", 	                  State = "Montana", 	                    StateOrNational = "State" },
        new Park { ParkId =116, 	Name = "Glacier", 	                          State = "Montana", 	                    StateOrNational = "National" },
        new Park { ParkId =117, 	Name = "Eugene T. Mahoney", 	                State = "Nebraska", 	                  StateOrNational = "State" },
        new Park { ParkId =118, 	Name = "Fort Robinson", 	                    State = "Nebraska", 	                  StateOrNational = "State" },
        new Park { ParkId =119, 	Name = "Wildcat Hills", 	                    State = "Nebraska", 	                  StateOrNational = "State" },
        new Park { ParkId =120, 	Name = "Lake Tahoe", 	                        State = "Nevada", 	                    StateOrNational = "State" },
        new Park { ParkId =121, 	Name = "Valley of Fire", 	                    State = "Nevada", 	                    StateOrNational = "State" },
        new Park { ParkId =122, 	Name = "Cave Lake Slate", 	                  State = "Nevada", 	                    StateOrNational = "State" },
        new Park { ParkId =123, 	Name = "Great Basin", 	                      State = "Nevada", 	                    StateOrNational = "National" },
        new Park { ParkId =124, 	Name = "Crawford Notch", 	                    State = "New Hampshire", 	              StateOrNational = "State" },
        new Park { ParkId =125, 	Name = "Franconia Notch", 	                  State = "New Hampshire", 	              StateOrNational = "State" },
        new Park { ParkId =126, 	Name = "Bear Brook", 	                        State = "New Hampshire", 	              StateOrNational = "State" },
        new Park { ParkId =127, 	Name = "Island Beach", 	                      State = "New Jersey", 	                StateOrNational = "State" },
        new Park { ParkId =128, 	Name = "Liberty State Park", 	                State = "New Jersey", 	                StateOrNational = "State" },
        new Park { ParkId =129, 	Name = "Pigeon Swamp", 	                      State = "New Jersey", 	                StateOrNational = "State" },
        new Park { ParkId =130, 	Name = "Bottomless Lakes", 	                  State = "New Mexico", 	                StateOrNational = "State" },
        new Park { ParkId =131, 	Name = "City of Rocks", 	                    State = "New Mexico", 	                StateOrNational = "State" },
        new Park { ParkId =132, 	Name = "Elephant Butte", 	                    State = "New Mexico", 	                StateOrNational = "State" },
        new Park { ParkId =133, 	Name = "Carlsbad Caverns", 	                  State = "New Mexico", 	                StateOrNational = "National" },
        new Park { ParkId =134, 	Name = "White Sands", 	                      State = "New Mexico", 	                StateOrNational = "National" },
        new Park { ParkId =135, 	Name = "Adirondack", 	                        State = "New York", 	                  StateOrNational = "State" },
        new Park { ParkId =136, 	Name = "Niagara Falls", 	                    State = "New York", 	                  StateOrNational = "State" },
        new Park { ParkId =137, 	Name = "Sterling Forest", 	                  State = "New York", 	                  StateOrNational = "State" },
        new Park { ParkId =138, 	Name = "Chimney Rock", 	                      State = "North Carolina", 	            StateOrNational = "State" },
        new Park { ParkId =139, 	Name = "Fort Macon", 	                        State = "North Carolina", 	            StateOrNational = "State" },
        new Park { ParkId =140, 	Name = "Hanging Rock", 	                      State = "North Carolina", 	            StateOrNational = "State" },
        new Park { ParkId =141, 	Name = "Great Smoky Mountains", 	            State = "North Carolina, Tennessee",    StateOrNational = "National" },
        new Park { ParkId =142, 	Name = "Fort Abraham Lincoln", 	              State = "North Dakota", 	              StateOrNational = "State" },
        new Park { ParkId =143, 	Name = "Little Missouri", 	                  State = "North Dakota", 	              StateOrNational = "State" },
        new Park { ParkId =144, 	Name = "Lake Metigoshe", 	                    State = "North Dakota", 	              StateOrNational = "State" },
        new Park { ParkId =145, 	Name = "Theodore Roosevelt", 	                State = "North Dakota", 	              StateOrNational = "National" },
        new Park { ParkId =146, 	Name = "Hocking Hills", 	                    State = "Ohio", 	                      StateOrNational = "State" },
        new Park { ParkId =147, 	Name = "Salt Fork", 	                        State = "Ohio", 	                      StateOrNational = "State" },
        new Park { ParkId =148, 	Name = "Punderson", 	                        State = "Ohio", 	                      StateOrNational = "State" },
        new Park { ParkId =149, 	Name = "Cuyahoga Valley", 	                  State = "Ohio", 	                      StateOrNational = "National" },
        new Park { ParkId =150, 	Name = "Beavers Bend", 	                      State = "Oklahoma", 	                  StateOrNational = "State" },
        new Park { ParkId =151, 	Name = "Lake Thunderbird", 	                  State = "Oklahoma", 	                  StateOrNational = "State" },
        new Park { ParkId =152, 	Name = "Robbers Cave", 	                      State = "Oklahoma", 	                  StateOrNational = "State" },
        new Park { ParkId =153, 	Name = "Ecola", 	                            State = "Oregon", 	                    StateOrNational = "State" },
        new Park { ParkId =154, 	Name = "Milo McIver", 	                      State = "Oregon", 	                    StateOrNational = "State" },
        new Park { ParkId =155, 	Name = "Smith Rock", 	                        State = "Oregon", 	                    StateOrNational = "State" },
        new Park { ParkId =156, 	Name = "Crater Lake", 	                      State = "Oregon", 	                    StateOrNational = "National" },
        new Park { ParkId =157, 	Name = "Cherry Springs", 	                    State = "Pennsylvania", 	              StateOrNational = "State" },
        new Park { ParkId =158, 	Name = "Cook Forest", 	                      State = "Pennsylvania", 	              StateOrNational = "State" },
        new Park { ParkId =159, 	Name = "Presque Isle", 	                      State = "Pennsylvania", 	              StateOrNational = "State" },
        new Park { ParkId =160, 	Name = "Beavertail", 	                        State = "Rhode Island", 	              StateOrNational = "State" },
        new Park { ParkId =161, 	Name = "Snake Den", 	                        State = "Rhode Island", 	              StateOrNational = "State" },
        new Park { ParkId =162, 	Name = "Colt", 	                              State = "Rhode Island", 	              StateOrNational = "State" },
        new Park { ParkId =163, 	Name = "Hunting Island", 	                    State = "South Carolina", 	            StateOrNational = "State" },
        new Park { ParkId =164, 	Name = "Mountain Bridge Wilderness Area",     State = "South Carolina", 	            StateOrNational = "State" },
        new Park { ParkId =165, 	Name = "Table Rock", 	                        State = "South Carolina", 	            StateOrNational = "State" },
        new Park { ParkId =166, 	Name = "Congaree", 	                          State = "South Carolina", 	            StateOrNational = "National" },
        new Park { ParkId =167, 	Name = "Custer", 	                            State = "South Dakota", 	              StateOrNational = "State" },
        new Park { ParkId =168, 	Name = "Bear Butte", 	                        State = "South Dakota", 	              StateOrNational = "State" },
        new Park { ParkId =169, 	Name = "Sica Hollow", 	                      State = "South Dakota", 	              StateOrNational = "State" },
        new Park { ParkId =170, 	Name = "Badlands", 	                          State = "South Dakota", 	              StateOrNational = "National" },
        new Park { ParkId =171, 	Name = "Wind Cave", 	                        State = "South Dakota", 	              StateOrNational = "National" },
        new Park { ParkId =172, 	Name = "Fall Creek Falls", 	                  State = "Tennessee", 	                  StateOrNational = "State" },
        new Park { ParkId =173, 	Name = "South Cumberland", 	                  State = "Tennessee", 	                  StateOrNational = "State" },
        new Park { ParkId =174, 	Name = "Roan Mountain", 	                    State = "Tennessee", 	                  StateOrNational = "State" },
        new Park { ParkId =175, 	Name = "Big Bend Ranch", 	                    State = "Texas", 	                      StateOrNational = "State" },
        new Park { ParkId =176, 	Name = "Palo Duro Canyon", 	                  State = "Texas", 	                      StateOrNational = "State" },
        new Park { ParkId =177, 	Name = "Falcon", 	                            State = "Texas", 	                      StateOrNational = "State" },
        new Park { ParkId =178, 	Name = "Big Bend", 	                          State = "Texas", 	                      StateOrNational = "National" },
        new Park { ParkId =179, 	Name = "Guadalupe Mountains", 	              State = "Texas", 	                      StateOrNational = "National" },
        new Park { ParkId =180, 	Name = "Virgin Islands", 	                    State = "U.S. Virgin Islands", 	        StateOrNational = "National" },
        new Park { ParkId =181, 	Name = "Dead Horse Point", 	                  State = "Utah", 	                      StateOrNational = "State" },
        new Park { ParkId =182, 	Name = "Goblin Valley", 	                    State = "Utah", 	                      StateOrNational = "State" },
        new Park { ParkId =183, 	Name = "Jordanelle Reservoir", 	              State = "Utah", 	                      StateOrNational = "State" },
        new Park { ParkId =184, 	Name = "Zion", 	                              State = "Utah", 	                      StateOrNational = "National" },
        new Park { ParkId =185, 	Name = "Arches", 	                            State = "Utah", 	                      StateOrNational = "National" },
        new Park { ParkId =186, 	Name = "Bryce Canyon", 	                      State = "Utah", 	                      StateOrNational = "National" },
        new Park { ParkId =187, 	Name = "Canyonlands", 	                      State = "Utah", 	                      StateOrNational = "National" },
        new Park { ParkId =188, 	Name = "Capitol Reef", 	                      State = "Utah", 	                      StateOrNational = "National" },
        new Park { ParkId =189, 	Name = "Ricker Pond", 	                      State = "Vermont", 	                    StateOrNational = "State" },
        new Park { ParkId =190, 	Name = "Smugglers’ Notch", 	                  State = "Vermont", 	                    StateOrNational = "State" },
        new Park { ParkId =191, 	Name = "Camel’s Hump", 	                      State = "Vermont", 	                    StateOrNational = "State" },
        new Park { ParkId =192, 	Name = "First Landing", 	                    State = "Virginia", 	                  StateOrNational = "State" },
        new Park { ParkId =193, 	Name = "Grayson Highlands", 	                State = "Virginia", 	                  StateOrNational = "State" },
        new Park { ParkId =194, 	Name = "Shenandoah River", 	                  State = "Virginia", 	                  StateOrNational = "State" },
        new Park { ParkId =195, 	Name = "Shenandoah", 	                        State = "Virginia", 	                  StateOrNational = "National" },
        new Park { ParkId =196, 	Name = "Cape Disappointment", 	              State = "Washington", 	                StateOrNational = "State" },
        new Park { ParkId =197, 	Name = "Deception Pass", 	                    State = "Washington", 	                StateOrNational = "State" },
        new Park { ParkId =198, 	Name = "Wallas Falls", 	                      State = "Washington", 	                StateOrNational = "State" },
        new Park { ParkId =199, 	Name = "Mount Rainier", 	                    State = "Washington", 	                StateOrNational = "National" },
        new Park { ParkId =200, 	Name = "North Cascades", 	                    State = "Washington", 	                StateOrNational = "National" },
        new Park { ParkId =201, 	Name = "Olympic", 	                          State = "Washington", 	                StateOrNational = "National" },
        new Park { ParkId =202, 	Name = "Blackwater Falls", 	                  State = "West Virginia", 	              StateOrNational = "State" },
        new Park { ParkId =203, 	Name = "Watoga", 	                            State = "West Virginia", 	              StateOrNational = "State" },
        new Park { ParkId =204, 	Name = "Babcock", 	                          State = "West Virginia", 	              StateOrNational = "State" },
        new Park { ParkId =205, 	Name = "New River Gorge", 	                  State = "West Virginia", 	              StateOrNational = "National" },
        new Park { ParkId =206, 	Name = "Devil’s Lake", 	                      State = "Wisconsin", 	                  StateOrNational = "State" },
        new Park { ParkId =207, 	Name = "Lakeshore", 	                        State = "Wisconsin", 	                  StateOrNational = "State" },
        new Park { ParkId =208, 	Name = "Peninsula", 	                        State = "Wisconsin", 	                  StateOrNational = "State" },
        new Park { ParkId =209, 	Name = "Glendo", 	                            State = "Wyoming", 	                    StateOrNational = "State" },
        new Park { ParkId =210, 	Name = "Seminoe", 	                          State = "Wyoming", 	                    StateOrNational = "State" },
        new Park { ParkId =211, 	Name = "Hot Springs", 	                      State = "Wyoming", 	                    StateOrNational = "State" },
        new Park { ParkId =212, 	Name = "Grand Teton", 	                      State = "Wyoming", 	                    StateOrNational = "National" },
        new Park { ParkId =213, 	Name = "Yellowstone", 	                      State = "Wyoming, Montana, Idaho",     	StateOrNational = "National" }
      );
    }
  }
}